### ISSUE TITLE
Error in running the docker build .

### ISSUE THREAD

**Issue by varamhcu** [sklasfeld/GreenscreenProject#1]
Dear Samantha, 

Thank you for the excellent publication and repository. I have gone through the theory and it will be extremely useful for my analysis. 

I had an issue while running the "sudo docker build ." command. Here I will attach the error on the terminal. Please look into it and let me know if I can fix the error. 

Excited to use this program on Osativa (rice) genome. 

Thank you
Here is the error.
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      CRITICAL: Python version must >= 3.6!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
The command '/bin/sh -c pip3 install --no-cache-dir --upgrade pip &&     pip3 install --no-cache-dir -r requirements.txt' returned a non-zero code: 1

**Comment by sklasfeld** [comment]
Hi, thank you so much for using Greenscreen. Have you tried updating your python version to a version greater than 3.6? It looks like your system is not yet compatible for docker to build the image. Let me know how it goes and good luck!

**Comment by varamhcu** [comment]
I cross-checked the version of python, it is 3.9.7. I re-run the 'docker build .' again. It resulted in the same error.

Thank you for reply

**Comment by sklasfeld** [comment]
To make sure there is nothing wrong with your docker installation, can you try to build a more simple docker image: https://docs.docker.com/language/python/build-images/

**Comment by varamhcu** [comment]
Thanks for the suggestion. I run this command "DOCKER_BUILDKIT=1 docker build ." It ended up with an error that is similar to the previous one(posted above).

Error:

Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'error'
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [1 lines of output]
    CRITICAL: Python version must >= 3.6!
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
------
executor failed running [/bin/sh -c pip3 install --no-cache-dir --upgrade pip &&     pip3 install --no-cache-dir -r requirements.txt]: exit code: 1


Please help me to fix this error. I cross-checked the python version is 3.8.10

**Comment by sklasfeld** [comment]
Rather than building the image yourself, try pulling the image with the following command:

 `docker pull sklasfeld/greenscreen`

Then you can generate a container by running the image with the command:

`docker run --name [CONTAINER_NAME] -i -t sklasfeld/greenscreen bash`

I hope this works

**Comment by varamhcu** [comment]
Yes. This worked for me. I will generate "green screens" and peak calling using my control data sets. 

I will get back to you if I have any doubts.

Thank you
